### ISSUE TITLE
#7 Todo

### ISSUE THREAD

**Issue by limjihun** [limjihun/GoldenFlag#8]
- [x] Modify projectile size
- [x] Create collision channel
- [x] Projectile offset
- [x] Projectile velocity & impact
